"""Add family and children tables

Revision ID: b9ff05469e24
Revises: 0001
Create Date: 2026-03-21 21:06:01.673180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ff05469e24'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_family', sa.Boolean(), nullable=False))
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_password_reset_token', table_name='users', postgresql_where='(password_reset_token IS NOT NULL)')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_password_reset_token', 'users', ['password_reset_token'], unique=False, postgresql_where='(password_reset_token IS NOT NULL)')
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.drop_column('users', 'has_family')
    # ### end Alembic commands ###
